Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    vb.cpus = 1
  end
  config.vm.define "router1" do |router1|
    router1.vm.box = "ubuntu/trusty64"
    router1.vm.hostname = "router1"
    router1.vm.network "private_network", virtualbox__intnet: "link0", ip: "192.168.1.1", auto_config: false
    router1.vm.network "private_network", virtualbox__intnet: "link1", ip: "192.168.2.1", auto_config: false
    router1.vm.provision "shell", path: "router1.sh"
    router1.vm.provision "shell", run: "always", path: "router1_netem.sh"
    router1.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host0" do |host0|
    host0.vm.box = "ubuntu/trusty64"
    host0.vm.hostname = "host0"
    host0.vm.network "private_network", virtualbox__intnet: "link0", ip: "192.168.1.22", auto_config: false
    host0.vm.provision "shell", path: "host0.sh"
    host0.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host1" do |host1|
    host1.vm.box = "ubuntu/trusty64"
    host1.vm.hostname = "host1"
    host1.vm.network "private_network", virtualbox__intnet: "link1", ip: "192.168.2.22", auto_config: false
    host1.vm.provision "shell", path: "host1.sh"
    host1.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
end
