Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    vb.cpus = 1
  end
  config.vm.define "r1" do |r1|
    r1.vm.box = "ubuntu/trusty64"
    r1.vm.hostname = "r1"
    r1.vm.network "private_network", virtualbox__intnet: "link0", ip: "192.168.1.1", auto_config: false
    r1.vm.network "private_network", virtualbox__intnet: "linkRs", ip: "192.168.2.1", auto_config: false
    r1.vm.provision "shell", path: "r1.sh"
    r1.vm.provision "shell", run: "always", path: "r1_netem.sh"
    r1.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host1" do |host1|
    host1.vm.box = "ubuntu/trusty64"
    host1.vm.hostname = "host1"
    host1.vm.network "private_network", virtualbox__intnet: "link0", ip: "192.168.1.22", auto_config: false
    host1.vm.provision "shell", path: "host1.sh"
    host1.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "r2" do |r2|
    r2.vm.box = "ubuntu/trusty64"
    r2.vm.hostname = "r2"
    r2.vm.network "private_network", virtualbox__intnet: "linkRs", ip: "192.168.2.11", auto_config: false
    r2.vm.network "private_network", virtualbox__intnet: "link1", ip: "192.168.3.1", auto_config: false
    r2.vm.provision "shell", path: "r2.sh"
    r2.vm.provision "shell", run: "always", path: "r2_netem.sh"
    r2.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
  config.vm.define "host2" do |host2|
    host2.vm.box = "ubuntu/trusty64"
    host2.vm.hostname = "host2"
    host2.vm.network "private_network", virtualbox__intnet: "link1", ip: "192.168.3.22", auto_config: false
    host2.vm.provision "shell", path: "host2.sh"
    host2.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end
end
